### ISSUE TITLE
Certain pages fail to migrate without showing any errors in the log

### ISSUE THREAD

**Issue by twozero6** [Kentico/xperience-by-kentico-kentico-migration-tool#303]
I am migrating 2 types that look something like the following in the tree:

ItemFolder
- ItemFolder
-- Item
-- Item
- ItemFolder
-- Item
-- Item

ItemFolder is being migrated automatically, with no custom mapping class.
Item is being migrated with a custom mapping class.

Items that are in the first nested ItemFolder work just fine - I am able to access them and see all of their data on the Content tab.
Items that are in the second nested ItemFolder cannot be accessed. As soon as I try to open the second ItemFolder, I get a 500 error in the event log and the folder just spins - I cannot access the Items. 

This is in the event log:

`
Description
An unhandled exception has occurred while executing the request.
Message: The virtual path must start with '~'. (Parameter 'virtualPath')

Exception type: System.ArgumentException
Stack trace:
at CMS.Helpers.Internal.VirtualContext.AddPathHash(String virtualPath)
at Kentico.Content.Web.Mvc.PreviewLinkGenerator.GeneratePreviewModePath(Int32 webPageItemId, String languageName, NameValueCollection virtualContextParams, NameValueCollection queryString, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Websites.WebPageActionsBuilder.CreateOpenPreviewInNewTabAction(WebPageAdminModel webPage, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Websites.WebPageActionsBuilder.AddOpenPreviewTab(List`1 actions, WebPageAdminModel webPage)
at Kentico.Xperience.Admin.Websites.WebPageActionsBuilder.BuildMenuActions(WebPageAdminModel webPage, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Websites.WebPageActionsBuilder.BuildForMenuInternal(WebPageAdminModel webPage, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Websites.WebPageStateProvider.GetStateInternal(WebPageAdminModel webPage, ContentItemWorkflowState workflowState, ContentItemStatus status, CancellationToken cancellationToken)
`

This is the log for migrating the folder in question:

`2024-11-20T08:53:09.4693772-05:00 (Migration.Tool.Source.Handlers.MigratePagesCommandHandler) [DBG] Page '"/Resource-Assets/COVID-19-Resources/COVID-19-Resource-Library-1"' migration (c406df39)
2024-11-20T08:53:09.4693888-05:00 (Migration.Tool.Common.MigrationProtocol.DebugMigrationProtocol) [DBG] FetchedSource: "Migration.Tool.Source.Model.ICmsTree": "CmsTreeK13 { NodeID = 5416, NodeAliasPath = /Resource-Assets/COVID-19-Resources/COVID-19-Resource-Library-1, NodeName = COVID - 19 AP Resource Library, NodeAlias = COVID-19-Resource-Library-1, NodeClassID = 5510, NodeParentID = 5989, NodeLevel = 3, NodeACLID = 74, NodeSiteID = 1, NodeGUID = 45e440c0-fed4-43c2-8008-1727c72206a7, NodeOrder = 1, IsSecuredNode = , NodeSKUID = , NodeLinkedNodeID = , NodeOwner = 82, NodeCustomData = , NodeLinkedNodeSiteID = , NodeHasChildren = True, NodeHasLinks = False, NodeOriginalNodeID = 5416, NodeIsACLOwner = False }" (7d1409a0)
2024-11-20T08:53:09.4725751-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemContentTypeID"' from '"DataClassInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4734106-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemContentFolderID"' from '"ContentFolderInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4734259-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemChannelID"' from '"ChannelInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4788194-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemCommonDataContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4793412-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemCommonDataContentLanguageID"' from '"ContentLanguageInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4829075-05:00 (Kentico.Xperience.UMT.InfoAdapter.ContentItemDataAdapter) [DBG] Mapping reference property '"ContentItemDataCommonDataID"' from '"ContentItemCommonDataInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4862967-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataModifiedByUserID"' from '"UserInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4868436-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetaDataContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4876590-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataContentLanguageID"' from '"ContentLanguageInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4884118-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataCreatedByUserID"' from '"UserInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4912586-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemWebsiteChannelID"' from '"WebsiteChannelInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4917401-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:09.4921914-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemParentID"' from '"WebPageItemInfo"' ObjectId (499526c0)`

This is one of the Items in the Folder (that I cannot access):

`2024-11-20T08:53:34.9424694-05:00 (Migration.Tool.Source.Handlers.MigratePagesCommandHandler) [DBG] Page '"/Resource-Assets/COVID-19-Resources/COVID-19-Resource-Library-1/In-Store-Protocols-Grocery-Retailer"' migration (c406df39)
2024-11-20T08:53:34.9425186-05:00 (Migration.Tool.Common.MigrationProtocol.DebugMigrationProtocol) [DBG] FetchedSource: "Migration.Tool.Source.Model.ICmsTree": "CmsTreeK13 { NodeID = 5498, NodeAliasPath = /Resource-Assets/COVID-19-Resources/COVID-19-Resource-Library-1/In-Store-Protocols-Grocery-Retailer, NodeName = In-Store Protocols Grocery Retailer, NodeAlias = In-Store-Protocols-Grocery-Retailer, NodeClassID = 5509, NodeParentID = 5416, NodeLevel = 4, NodeACLID = 74, NodeSiteID = 1, NodeGUID = cc0c69a6-a7f1-497b-9169-cf322a49f199, NodeOrder = 1, IsSecuredNode = , NodeSKUID = , NodeLinkedNodeID = , NodeOwner = 82, NodeCustomData = , NodeLinkedNodeSiteID = , NodeHasChildren = False, NodeHasLinks = False, NodeOriginalNodeID = 5498, NodeIsACLOwner = False }" (7d1409a0)
2024-11-20T08:53:34.9457159-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemContentTypeID"' from '"DataClassInfo"' ObjectId (499526c0)
2024-11-20T08:53:34.9466565-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemContentFolderID"' from '"ContentFolderInfo"' ObjectId (499526c0)
2024-11-20T08:53:34.9466715-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemChannelID"' from '"ChannelInfo"' ObjectId (499526c0)
2024-11-20T08:53:34.9553264-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9574318-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextAreaControl, TargetFormComponent = Kentico.Administration.TextArea, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9595384-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9616266-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9637038-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextAreaControl, TargetFormComponent = Kentico.Administration.TextArea, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9683310-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9704852-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9720231-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9733023-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9750434-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextAreaControl, TargetFormComponent = Kentico.Administration.TextArea, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9770512-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = boolean, TargetDataType = boolean, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.Checkbox, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9792365-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9814210-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9837161-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9857305-05:00 (Migration.Tool.Source.Mappers.ContentItemMapper) [WRN] Value is not contained in source, field '"SeoFacebookAppId"' (747f23bb)
2024-11-20T08:53:34.9858050-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9880862-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9903505-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9926665-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9949717-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9973956-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = RadioButtonsControl, TargetFormComponent = Kentico.Administration.RadioGroup, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:34.9996613-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = RadioButtonsControl, TargetFormComponent = Kentico.Administration.RadioGroup, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0020343-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0044101-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = longtext, TargetDataType = richtexthtml, SourceFormControl = HtmlAreaControl, TargetFormComponent = Kentico.Administration.RichTextEditor, Actions = System.String[], FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0045706-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = longtext, TargetDataType = richtexthtml, SourceFormControl = HtmlAreaControl, TargetFormComponent = Kentico.Administration.RichTextEditor, Actions = System.String[], FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0046470-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = RadioButtonsControl, TargetFormComponent = Kentico.Administration.RadioGroup, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0047277-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = datetime, TargetDataType = datetime, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.DateTimeInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0047891-05:00 (Migration.Tool.Source.Mappers.ContentItemMapper) [WRN] Value is not contained in source, field '"ResourceItemExternalUrl"' (747f23bb)
2024-11-20T08:53:35.0048653-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0049512-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0051127-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0052214-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = TextBoxControl, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0053150-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = text, TargetDataType = text, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextInput, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0053995-05:00 (Migration.Tool.KXP.Api.Services.CmsClass.FieldMigrationService) [DBG] Field migration matched: '"BuiltIn"', "FieldMigration { SourceDataType = longtext, TargetDataType = longtext, SourceFormControl = #any#, TargetFormComponent = Kentico.Administration.TextArea, Actions = , FieldNameRegex = , Rank = 100000 }" (9835e28d)
2024-11-20T08:53:35.0054669-05:00 (Migration.Tool.Source.Mappers.ContentItemMapper) [WRN] Value is not contained in source, field '"DocumentName"' (747f23bb)
2024-11-20T08:53:35.0071869-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemCommonDataContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0082279-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemCommonDataContentLanguageID"' from '"ContentLanguageInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0239613-05:00 (Kentico.Xperience.UMT.InfoAdapter.ContentItemDataAdapter) [DBG] Mapping reference property '"ContentItemDataCommonDataID"' from '"ContentItemCommonDataInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0310098-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataModifiedByUserID"' from '"UserInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0318226-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetaDataContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0329310-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataContentLanguageID"' from '"ContentLanguageInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0340645-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"ContentItemLanguageMetadataCreatedByUserID"' from '"UserInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0380111-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemWebsiteChannelID"' from '"WebsiteChannelInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0389332-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemContentItemID"' from '"ContentItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0398824-05:00 (Kentico.Xperience.UMT.InfoAdapter.GenericInfoAdapter) [DBG] Mapping reference property '"WebPageItemParentID"' from '"WebPageItemInfo"' ObjectId (499526c0)
2024-11-20T08:53:35.0593038-05:00 (Migration.Tool.Source.Handlers.MigratePagesCommandHandler) [WRN] Cannot migrate url for document '5491' / node '5498', source instance context is not available or set-up correctly - default fallback will be used. (77b02db8)`

**Comment by twozero6** [comment]
I think I found the issue: in the source, the project is using custom routing with a fairly complex custom macro to generate the URL for this type. I confirmed by switching back to page tree routing and re-running the migration - now all of the pages are working after the migration. I don't know if custom macro routing is fully supported so I'll leave this open in case you want to take a look.
