### ISSUE TITLE
Error when using ContentItemSelectorComponent with a migrated content item

### ISSUE THREAD

**Issue by twozero6** [Kentico/xperience-by-kentico-kentico-migration-tool#322]
I migrated a "Feature" content type and its items from K13 to XbyK 27.9.0. I am now testing the migration, and as part of that process, I selected one of the migrated items in a widget property and then attempted to query the database using that selected item. When I select a migrated item and press Save in the widget settings, I get a 500 error. If I manually create a new item of that same type in the XbyK project, I can select it and use it without errors.

Here is how my widget property looks:

```
       [ContentItemSelectorComponent(
            Feature.CONTENT_TYPE_NAME,
            ExplanationText = "Create or select a Feature to display.",
            Label = "Feature Item",
            MinimumItems = 0,
            MaximumItems = 1,
            Order = 1)]
        public IEnumerable<ContentItemReference> ContentToDisplay { get; set; } = Enumerable.Empty<ContentItemReference>();
```

This is the error I am getting:

```
Description
An unhandled exception has occurred while executing the request.
Message: Cannot find a web page item with the ContentItemID 710.

Exception type: System.InvalidOperationException
Stack trace:
at Kentico.Xperience.Admin.Websites.WebPageItemNavigationProvider.GetSlugs(Int32 contentItemID, String languageName, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Websites.WebPageItemNavigationProvider.GetEditNavigation(Int32 contentItemID, String languageName, PreferredTab preferredTab, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Base.UIPages.ContentItemNavigationPathRetriever.GetEditNavigationPath(Int32 contentItemId, Int32 languageId, Int32 channelId, PreferredTab preferredTab, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProvider.GetItemNavigateToPath(Int32 languageId, Int32 contentItemId, Int32 channelId, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProviderBase.GetItem(IDataContainer dataContainer, Int32 sourceLanguageId, IReadOnlyCollection`1 liveSiteFallbackChain, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Base.Components.ContentItemSelectorItemProviderBase.Get(IEnumerable`1 references, Int32 contentLanguageId, CancellationToken cancellationToken)
at Kentico.Xperience.Admin.Base.Forms.ContentItemSelectorComponentBase`1.SetItems(ContentItemSelectorClientProperties clientProperties)
at Kentico.Xperience.Admin.Base.Forms.ContentItemSelectorComponentBase`1.ConfigureClientProperties(ContentItemSelectorClientProperties clientProperties)
at Kentico.Xperience.Admin.Base.Forms.FormComponent`3.GetClientProperties()
at Kentico.Xperience.Admin.Base.Forms.FormComponent`3.Kentico.Xperience.Admin.Base.Forms.IFormItem.GetClientProperties()
at Kentico.Xperience.Admin.Base.Forms.FormItemExtensions.<>c.<<GetClientProperties>b__4_0>d.MoveNext()
```

**Comment by liparova** [comment]
Thank you for bringing this to our attention. We'll examine it internally and keep you updated on our progress.

**Comment by bluemodus-mwills** [comment]
@liparova -- just like #327 , this issue is holding us up on some migration work. Any news?

**Comment by liparova** [comment]
We apologize for the delay; we are currently focused on completing an important feature request. We’ll review it next week.

**Comment by akfakmot** [comment]
@twozero6 If possible, can you please provide a database image? Thank you

**Comment by akfakmot** [comment]
Hello @twozero6 ,

I believe I've found the cause. I will fix it in Migration Tool, but if you could have a quick peek into the database that has this issue, it would help fast forward in case my finding isn't your issue's root cause.... 

Can you confirm that the failing content item's row in CMS_ContentItem has ContentItemChannelID <>NULL and that the manually created one has it =NULL?

I tried looking it up in database migrated from the source you provided, but wasn't able to find content item of type feature and this particular ID there.

Thanks

**Comment by twozero6** [comment]
Hi @akfakmot,

That's correct - I checked, and the failing one has 1 as the value; the manually created items have a NULL value. 

I can manually update the reusable items for now but it would be nice if the tool could do it.

Thanks again!

**Comment by akfakmot** [comment]
@twozero6  I tried it also on my ad-hoc widget and changing channel ID to NULL makes it work.

This issue is already fixed in yesterday's version release (2.1.0). However re-running migration wouldn't patch channel ID to NULL, because `ContentItemModel.ContentItemChannelID = null` in the current semantics means _field not specified_ and not _set to null_. The field will be properly set to null on new migrations, but not on rerun.

As changing the semantics is out of scope of this task, I willingly accept your proposition to manually update the columns, e.g. by the following command.

`UPDATE CMS_ContentItem SET ContentItemChannelID = NULL WHERE ContentItemIsReusable <> 0`

Let me know if you need further assistance on this issue.

Thank you for helping to make our product better.

**Comment by twozero6** [comment]
@akfakmot this issue seems to be resolved. I appreciate your help!

**Comment by akfakmot** [comment]
Thank you @twozero6 . I appreciate your report and testing the results
